### ISSUE TITLE
No need to keep pywapi in this repo

### ISSUE THREAD

**Issue by petebachant** [LivingBridge/WeatherAlert#1]
It's actually not being used here anyway, since it has to be installed. However, it should be listed as a dependency in the README. 

It looks like pywapi is not being maintained, so it might be smart to create a new repo for it here on GitHub. This would allow it to be installed with `pip`.

**Comment by petebachant** [comment]
I just exported the `python-weather-api` source code to https://github.com/LivingBridge/python-weather-api. Now people can install the package from the shell with

```
pip install https://github.com/LivingBridge/python-weather-api/archive/master.zip
```

**Comment by petebachant** [comment]
Actually it appears to be up on GitHub by the original author: https://github.com/jtasker/python-weather-api, so it's possible to install via

```
pip install https://github.com/jtasker/python-weather-api/archive/master.zip
```

**Comment by iangagnon** [comment]
Ok so typical procedure for something like this is to just reference it in the repo's readme as a dependency?

**Comment by petebachant** [comment]
Yep. Or with packages that must be install with `pip` you can list them in a `requirements.txt` file.

**Comment by iangagnon** [comment]
Updated readme with instructions for where to find and install pywapi.

**Comment by petebachant** [comment]
Looks like it's still being tracked by Git. Try

```
git rm -r pywapi-0.3.8
```

Then make a commit.

**Comment by iangagnon** [comment]
Ahh yes, that worked. Thanks Pete!
